name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_task:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            export DOCKER_API_VERSION=1.44
            cd ~/soluciones-tecnologicas-futuro/soluciones-tecnologicas-futuro
            git reset --hard
            git pull origin main
            # Si usa bun, asegúrese de que esté instalado en el servidor
            # pero para su Docker lo que importa es esto:
            docker-compose build --no-cache
            docker-compose up -d
            docker ps
            echo "✓ Proceso completado socio"