name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd soluciones-tecnologicas-futuro
            git reset --hard
            git pull origin main
            docker-compose build --no-cache
            docker-compose up -d
            docker ps -a
            echo "✓ Deployment completado exitosamente"
